# Generated by Django 3.2.16 on 2024-10-24 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20241024_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='name',
        ),
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='title',
            field=models.CharField(default='Default Title', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.group'),
        ),
    ]
